name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
   VERSION_TAG: v6.3.11b
   
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/openkm-debian-pg:$VERSION_TAG
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_TOKEN }} 
    - name: Push the Docker image to the Docker Hub
      run: docker push ${{ secrets.DOCKER_USER }}/openkm-debian-pg:$VERSION_TAG
    - name: Build the Docker image with tag 'latest'
      run: docker tag ${{ secrets.DOCKER_USER }}/openkm-debian-pg:$VERSION_TAG ${{ secrets.DOCKER_USER }}/openkm-debian-pg:latest
    - name: Push the Docker image with tag 'latest' to the Docker Hub
      run: docker push ${{ secrets.DOCKER_USER }}/openkm-debian-pg:latest
